config_terminal:
  configIcon: //android.widget.TextView[@text="Configurações"]
  configIconAlternative: //android.widget.TextView[@content-desc="Configurações"]
  aboutDevice: //android.widget.TextView[contains(@text, "Sobre o dispositivo")]
  aboutDeviceText: //android.widget.TextView[@resource-id="android:id/title" and @text="Nome do dispositivo"]
  deviceName: //android.widget.TextView[@resource-id="android:id/summary" and @text="TS-G820"]
  versaoAndroid: //android.widget.TextView[@resource-id="android:id/title" and @text="Versão do Android"]
  numberAndroidVersion: //android.widget.TextView[@resource-id="android:id/summary" and @text="13"]
  nCompilacaoFirmware: //android.widget.TextView[@resource-id="android:id/title" and @text="Número da compilação do firmware"]
  versionFirmware: //android.widget.TextView[@resource-id="android:id/summary"][3]
  versionHardware: //android.widget.TextView[@resource-id="android:id/title" and @text="Versão do hardware"]
  numberHardwareVersion: //android.widget.TextView[@resource-id="android:id/summary"][4]
  secaoNumeroSerie: //android.widget.TextView[@resource-id="android:id/title" and @text="Número de Série"]
  numeroSerie: //android.widget.TextView[@resource-id="android:id/summary" and @text="4101012546000945"]
  secaoNumeroVersao: //android.widget.TextView[@resource-id="android:id/title" and @text="Número da versão"]
  numeroVersao: //android.widget.TextView[@resource-id="android:id/summary" and @text="SQ29MB_GERTEC_G820_V017_user"]
  btnVoltar: //android.widget.ImageButton[@content-desc="Navegar para cima"]